### ISSUE TITLE
Updating an entity that violates a unique constraint gives no indication the violation occurred

### ISSUE THREAD

**Issue by kgreen24** [nhibernate/fluent-nhibernate#355]
I have an entity that has a unique constraint on a name property:

`Map(x => x.Name).Unique();`

My backing database is SQL Server 2014.

When I try to add a new record with a name that already exists in the db, I get a nice exception that I can catch and deal with. However, if I update an entity with the name of an already existing entity and try to persist it, there is no exception thrown anywhere or otherwise any indication given that the constraint was violated. Code execution continues as normal, and the row in the db is just not updated.

There should be a way to catch and deal with constraint violation errors on update as there is with add.

**Comment by chester89** [comment]
@kgreen24 sorry I haven't seen that issue sooner. What does NHibernate people say about this? Something tells me it's not a fluent problem

**Comment by hazzik** [comment]
FluentNHibernate is a mapping generator tool. Not the ORM itself. 

Please post on the [nhusers group](https://groups.google.com/forum/#!forum/nhusers) with requested details.

**Comment by MichaelRodrigueess0s1** [comment]
I know the fluent Nhibernate is a mapping generator tool. Not the NORM itself. but the problem still occurring just when using the fluent Nhibernate. and your response does not help in anything

**Comment by oskarb** [comment]
Nevertheless, it's unlikely to be a problem in FluentNHibernate.

> still occurring just when using the fluent Nhibernate.

"Just when".. Are you actually saying that the problem doesn't occur if you
do the same mapping using some other mapping API? Though for now I suspect
that it was an unintended implication.

I suspect the problem isn't in NHibernate either. The constraint is checked
by the database software. And this is very common functionality, it would
at least be very surprising for that not to work.

I think a more likely explanation could be that the update isn't actually
flushed to the database, because for whatever reason your code doesn't do
anything that will trigger the flush. Or secondly, that there is an
exception but your code somewhere catch and drop it.
