### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by danilobreda** [nhibernate/fluent-nhibernate#459]
A lot of projects use fluent nhibernate but when we have some problems with new versions it takes ages for somebody to appears and accept the pullrequest 
An example is the #453 

What options do we have to solve this problem?

**Comment by pettersoft** [comment]
I'm curious as well. We are currently using a custom build at the office so we can utilize NHibernate 5.2. It would be preferable to use this instead.

**Comment by danilobreda** [comment]
Maybe we should need to go with Nhibernate own Mapping ByCode? The problem is that the migration from Fluent to nhibernate bycode is not a easy task.
Nhibernate MappingByCode does not have a lot of documentation.

**Comment by fredericDelaporte** [comment]
A discussion about this subject has been opened on the [NHibernate development list](https://groups.google.com/g/nhibernate-development/c/lhNOJuUatWA/m/BRjf7j2-BAAJ).

**Comment by jrgcubano** [comment]
Hi there @fredericDelaporte @danilobreda, 

Sounds like a good idea to me. I started a few years ago requesting the ownership of the project from James and Gleb to give it extra life, mostly with the migration to NETCore. I am sorry I could not continue to maintain it, and that's mostly because I'm not using hibernate in the projects I'm working on right now. I would be delighted and I think I speak on behalf of James and Gleb to share ownership with someone who can give continuity to the project, and if it were directly in NHibernate organisation, much better.

**Comment by pettersoft** [comment]
> A discussion about this subject has been opened on the [NHibernate development list](https://groups.google.com/g/nhibernate-development/c/lhNOJuUatWA/m/BRjf7j2-BAAJ).

Great news Frederic!

**Comment by danilobreda** [comment]
Fluent-Nhibernate is now inside Nhibernate repository! 👍 
Thanks to the **nhibernate** for allowing this project to continue.
### The community thanks you!
